# os settings 
os: linux
dist: xenial # Use Ubuntu 16.04 as our Travis CI environment

# lang settings
language: python
python: 
     -3.7
     
env: YELLOW="\033[1;33m" \
     NC="\033[0m" # No Color

install:
  - pip install --upgrade pylint # Use pip to install Pylint

#before_script:

script:
  # Lint the Python files.
  - echo -e "${YELLOW}Analyzing code...${NC}" && pylint --errors-only *.py
